server.servlet.context-path: /marvel

character.request.limit: 100

feign.client.config:
  characters.errorDecoder: com.growin.marvel.exception.CharacterErrorDecoder
  translation.errorDecoder: com.growin.marvel.exception.TranslationErrorDecoder

